sudo: false
language: ruby
rvm: 2.6.0
cache:
  bundler: true
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rubocop
  - bundle exec rspec
  - bundle exec rubycritic --no-browser -s 90 -f console


